[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
    venv/
    | \.venv/
    | extracted_files/
    | DATA/runtime/
    | \.git/
    | __pycache__/
    | \.pytest_cache/
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = [
    "venv/*",
    ".venv/*",
    "extracted_files/*", 
    "DATA/runtime/*",
    "__pycache__/*",
    ".pytest_cache/*"
]

[tool.flake8]
max-line-length = 88
max-complexity = 12
exclude = [
    "venv",
    ".venv", 
    "__pycache__",
    "extracted_files",
    "DATA/runtime"
]
