[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
  | extracted_files
  | DATA/runtime
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip = ["venv", ".venv", "extracted_files", "DATA/runtime"]
