name: Bug Report
description: Report a bug or issue with the Zeek-YARA Integration platform
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! This helps improve the platform for everyone.
        
        Before submitting, please:
        1. Check if a similar issue already exists
        2. Try the latest version if possible
        3. Include as much detail as possible to help us reproduce the issue

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug in 1-2 sentences
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Output
      description: Copy and paste any relevant log output, error messages, or screenshots
      render: shell
      placeholder: Paste error logs, stack traces, or attach screenshots here

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Core Scanner
        - YARA Rules
        - Zeek Integration
        - Web Interface
        - Tutorial System
        - CLI Tools
        - Documentation
        - Installation/Setup
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (minor inconvenience)
        - Medium (affects functionality)
        - High (major feature broken)
        - Critical (system unusable)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the platform are you using?
      placeholder: e.g., v1.0.0, main branch, commit hash
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - macOS
        - Windows
        - Docker Container
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What Python version are you using?
      placeholder: e.g., 3.8.10, 3.9.7
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information (Docker version, dependencies, etc.)
      placeholder: |
        - Docker version: 20.10.8
        - Zeek version: 4.2.0
        - YARA version: 4.1.3
        - Other relevant details

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, workarounds, or related issues
      placeholder: Add any other context about the problem here

  - type: checkboxes
    id: terms
    attributes:
      label: Submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have provided all requested information
          required: true
        - label: I understand this is an educational platform and will be patient with response times
          required: true
        - label: I am willing to provide additional information if needed
          required: true