blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/russellsmith/zeek_yara_integration/discussions
    about: Ask questions, share ideas, and engage with the community
  - name: Discord Community
    url: https://discord.gg/your-discord-link
    about: Real-time chat with the community and maintainers
  - name: Documentation
    url: https://github.com/russellsmith/zeek_yara_integration/tree/main/docs
    about: Check our documentation for guides, tutorials, and reference materials